import {Apple} from "./apple";

export const Iphon: Apple[] = [
  {
    id: '0',
    name: 'Iphon 13 PRO MAX',
    image: '/assets/iphons/13PROMAX.jpg',
    featured: true,
    label: 'Телефон',
    price: '3300',
  },
  {
    id: '1',
    name: 'Iphon 13 PRO',
    image: '/assets/iphons/13PRO.jpg',
    featured: false,
    label: 'Телефон',
    price: '3100',
  },
  {
    id: '2',
    name: 'Iphon 13',
    image: '/assets/iphons/13.jpg',
    featured: false,
    label: 'Телефон',
    price: '2200',
  },

  {
    id: '3',
    name: 'Iphon 13 MINI',
    image: '/assets/iphons/13MINI.jpg',
    featured: false,
    label: 'Телефон',
    price: '1800',
  },
  {
    id: '4',
    name: 'Iphon 12 PRO MAX',
    image: '/assets/iphons/12PROMAX.jpg',
    featured: false,
    label: 'Телефон',
    price: '3200',
  },
  {
    id: '5',
    name: 'Iphon 12 PRO',
    image: '/assets/iphons/12PRO.jpg',
    featured: false,
    label: 'Телефон',
    price: '3000',
  },
  {
    id: '6',
    name: 'Iphon 12',
    image: '/assets/iphons/12.jpg',
    featured: false,
    label: 'Телефон',
    price: '2500',
  },
  {
    id: '7',
    name: 'Iphon 12 MINI',
    image: '/assets/iphons/12MINI.jpg',
    featured: false,
    label: 'Телефон',
    price: '1550',
  },
  {
    id: '8 ',
    name: 'Iphon 11 PRO MAX',
    image: '/assets/iphons/11PROMAX.jpg',
    featured: false,
    label: 'Телефон',
    price: '2450',
  },
  {
    id: '9 ',
    name: 'Iphon 11 PRO',
    image: '/assets/iphons/11PRO.jpg',
    featured: false,
    label: 'Телефон',
    price: '2200',
  },
  {
    id: '10 ',
    name: 'Iphon 11',
    image: '/assets/iphons/11.jpg',
    featured: false,
    label: 'Телефон',
    price: '1500',
  },
];
